### ISSUE TITLE
Update tubular repo to use boto3

### ISSUE THREAD

**Issue by dianakhuang** [openedx-unsupported/tubular#629]
We are seeing failures in deployment of our EC2 instances due to our old `boto` library failing to pull tags from AWS. We would like to upgrade this library across all of tubular to use `boto3`, the newer library that is better supported.

Acceptance Criteria
- [x] Fix unit tests that are broken due to our hotfixing to get the code upgraded to boto3.
- [x] Use `boto3` instead of `boto` in all of this repo.
- [x] Remove `boto` as a dependency of the repo.

**Comment by jmbowman** [comment]
@iamsobanjaved Should this be closed?  (Moving items on the board doesn't auto-close the issue, although closing the issue automatically updates the board.)

**Comment by awais786** [comment]
yes, It should be close.
